// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKp1kS1O5Amy96s95m4v46L5pFuAbwBaw',
    appId: '1:1006790015270:web:b10cd18db646015313e9e7',
    messagingSenderId: '1006790015270',
    projectId: 'playfolio-5a00c',
    authDomain: 'playfolio-5a00c.firebaseapp.com',
    storageBucket: 'playfolio-5a00c.firebasestorage.app',
    measurementId: 'G-FEC5RE8TC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6DGaJPYrSqUSK6Vo0fpFe7w7zNmi506M',
    appId: '1:1006790015270:android:794a8a97a5641ae513e9e7',
    messagingSenderId: '1006790015270',
    projectId: 'playfolio-5a00c',
    storageBucket: 'playfolio-5a00c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVK4W2vEvMzbFJO2Hr_nXwjCAe3gB7t3Q',
    appId: '1:1006790015270:ios:c52d1a822344963813e9e7',
    messagingSenderId: '1006790015270',
    projectId: 'playfolio-5a00c',
    storageBucket: 'playfolio-5a00c.firebasestorage.app',
    iosBundleId: 'com.example.playfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVK4W2vEvMzbFJO2Hr_nXwjCAe3gB7t3Q',
    appId: '1:1006790015270:ios:c52d1a822344963813e9e7',
    messagingSenderId: '1006790015270',
    projectId: 'playfolio-5a00c',
    storageBucket: 'playfolio-5a00c.firebasestorage.app',
    iosBundleId: 'com.example.playfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKp1kS1O5Amy96s95m4v46L5pFuAbwBaw',
    appId: '1:1006790015270:web:16ee2b2b45af727713e9e7',
    messagingSenderId: '1006790015270',
    projectId: 'playfolio-5a00c',
    authDomain: 'playfolio-5a00c.firebaseapp.com',
    storageBucket: 'playfolio-5a00c.firebasestorage.app',
    measurementId: 'G-LBBB87EWZZ',
  );
}
